Logic for allowing restrict to folder parameter #3744
hannonhill/tinymce pull request #3
Opened 2019-09-18 15:30 UTC by nadirayasmeen

**Before submitting a pull request** please do the following:

1. Fork [the repository](https://github.com/tinymce/tinymce) and create your branch from `master`
2. Have you added some code that should be tested? Write some tests! (Are you unsure how to write the test you want to write, ask us for help!)
3. Ensure that the tests pass: `grunt test`
4. Ensure that your code passes the linter: `grunt lint`
5. Make sure to sign the CLA.

2019-09-18 15:32 UTC, rgriffith requested changes

2019-09-18 15:32 UTC, rgriffith commented on src/plugins/image/src/main/js/ui/Dialog.js
> +        if (Settings.getRestrictToFolderId(editor)) {
Let's save this to a variable instead of calling it twice. I don't think there's much overhead, but a bit more DRY.

2019-09-30 23:16 UTC, merged

2019-10-01 15:05 UTC, bradical commented
@nadirayasmeen What are we looking at here? This is a plugin in TinyMCE right? How does the restriction stuff come into play with the plugin?

2019-10-01 15:10 UTC, nadirayasmeen commented
Yes, when there is a restrict to folder specified for a WYSIWYG in a data definition, the image and link chooser selections will be limited to the restrict to folder.

2019-10-01 15:11 UTC, bradical commented
Got it! Thanks for clarifying.

2019-10-01 15:12 UTC, bradical commented
So are we effectively just passing that information along to the chooser panel here? Or does this actually affect the WYSIWYG interface in anyway?

2019-10-01 15:14 UTC, nadirayasmeen commented
> So are we effectively just passing that information along to the chooser panel here? 
Correct, just passing along to the chooser panel. The interface isn't affected.